server:
  port: ${PORT:8080}

spring:
  application:
    name: manager-user-api
  datasource:
    username: ${DB_USERNAME:app-manager-user}
    password: ${DB_PASSWORD:G&k1>qHB>s<qkJ:D10dkI374}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db-manager-user}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    problemdetails:
      enabled: true

logging:
  pattern:
    level: '[${spring.application.name:},%X{traceId},%X{spanId}]'

management:
  endpoints:
    web:
      exposure:
        include: 'info, health, metrics'
  endpoint:
    health:
      show-details: always
  health:
    diskSpace:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
